# Official docker image.
image: docker:latest

services:
  - docker:dind

stages:
  - build

variables:
  APPIMAGE_NAME:   "$CI_REGISTRY_USER/$CI_PROJECT_NAME:$CI_PROJECT_ID"
  DOCKER_DRIVER: overlay2
  KUBE_CONFIG_FILE: /Users/srajeshkumar/.kube/config

before_script:
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" index.docker.io

build-master:
  stage: build
  tags:
    - build
  script:
    - docker build --pull -t "$APPIMAGE_NAME" .
    - docker push "$APPIMAGE_NAME"
    - kubectl get ns
  only:
    - master
