variables:
  KUBE_CONFIG_FILE: /Users/srajeshkumar/.kube/config
  KUBE_CONTEXT: workload-knv-admin@workload-knv

kubectl-test:
  tags:
    - gcrkube
  script:
    - env
    - kubectl --help
  only:
    - master