# Official docker image.
image: docker:latest

services:
  - docker:dind

variables:
  APPIMAGE_NAME:   "$CI_REGISTRY_USER/$CI_PROJECT_NAME:$CI_PROJECT_ID"

stage: 
  - build

before_script:
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY_URL"

build-master:
  stage: build
  script:
    - docker build --pull -t "$APPIMAGE_NAME" .
    - docker push "$APPIMAGE_NAME"
  only:
    - master
