apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: sit
namePrefix: hello-
commonLabels:
  app: hello

resources:
- service.yml
- deployment.yml

images:
- name: appImage
  newName: txconsole/hello-app
  newTag: "1.0"
